import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NotificationProvider } from "@/contexts/NotificationContext";
import AppProvider from "@/contexts/AppProvider";
import Notifications from "@/components/Notifications";
import { Analytics } from "@vercel/analytics/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: {
    default: "JamConnect - Connect, Collaborate, Create Music",
    template: "%s | JamConnect"
  },
  description: "Join JamConnect to discover musicians, create jam sessions, and collaborate with artists in your area. Connect with fellow musicians and bring your music to life.",
  keywords: ["musicians", "jam sessions", "music collaboration", "connect musicians", "music community", "band finder", "music events"],
  authors: [{ name: "JamConnect Team" }],
  creator: "JamConnect",
  publisher: "JamConnect",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://jamconnect.shivamjaiswal.in",
    siteName: "JamConnect",
    title: "JamConnect - Connect, Collaborate, Create Music",
    description: "Discover musicians, create jam sessions, and collaborate with artists worldwide.",
    images: [
      {
        url: "/og-image.jpg", // Add your OG image
        width: 1200,
        height: 630,
        alt: "JamConnect - Music Collaboration Platform",
      },
    ],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.ico",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NotificationProvider>
          <AppProvider>
            {children}
            <Notifications/>
           </AppProvider>
        </NotificationProvider>
        <Analytics />
      </body>
    </html>
  );
}
